Update readMe
snappmarket/frontend-toolbox pull request #186
Opened 2020-04-21 07:05 UTC by MostafaRastegar

2020-04-21 07:49 UTC, rezaerami commented
thank you for the docs, but by documentation, I meant docz, so we can have a demo also.

2020-04-21 13:25 UTC, MostafaRastegar commented
Add mdx

2020-04-21 20:51 UTC, sayjeyhi commented on packages/ui/packages/Carousel/index.mdx
> +            >
has mdx pasring error:

```bash
   90 |     ....
    91 |     nextArrow={
  
  
    SyntaxError: unknown: Expected corresponding JSX closing tag for <Carousel> (8  8:86)
      86 | `}</code></pre>
      87 | <p>{`next:
    > 88 | add custom icon DOM or Component for nextArrow,prevArrow on `}<Carousel  >{` attribute`}</p>
         |                                                                                         ^
      89 | <pre><code parentName="pre" {...{"className":"language-es6"}}>{`  <Caro  usel
      90 |     ....
      91 |     nextArrow={/home/runner/work/frontend-toolbox/frontend-toolbox/pack  ages/ui/packages/Carousel/README.md: unknown: Expected corresponding JSX closi  ng tag for <Carousel> (88:86)
      86 | `}</code></pre>
      87 | <p>{`next:
    > 88 | add custom icon DOM or Component for nextArrow,prevArrow on `}<Carousel  >{` attribute`}</p>
         |                                                                                         ^
      89 | <pre><code parentName="pre" {...{"className":"language-es6"}}>{`  <Caro  usel
      90 |     ....
      91 |     nextArrow={
```

detailed message [here](https://github.com/snappmarket/frontend-toolbox/pull/186/checks?check_run_id=605308133)

2020-04-21 20:52 UTC, sayjeyhi requested changes
your PR has build error

2020-04-22 08:16 UTC, MostafaRastegar commented on packages/ui/packages/Carousel/index.mdx
> +            >
fixed

2020-04-27 17:38 UTC, rezaerami commented
all the build and docz issues are fixed now, but the only issue i see is the navigation buttons
in the RTL slider, when i click on the first page button, it goes to that page but it doesn't activate the related button, also when i use arrow button to go to the first page of slider, it happens again and the first navigation button wont be activated, but when it's auto sliding to that, there's no problem

2020-04-28 15:19 UTC, closed without merging