Add integerInput on toolbox
snappmarket/frontend-toolbox pull request #260
Opened 2020-06-24 08:37 UTC by MostafaRastegar

2020-06-24 09:23 UTC, rezaerami commented
please add tests at least with 30% coverage

2020-06-24 10:23 UTC, sayjeyhi commented on packages/ui/packages/IntegerInput/src/index.js
> +  type,
This is better to handle with a prop on `Input` component, this could increase size without any strong reason

2020-06-24 10:24 UTC, sayjeyhi requested changes
⛓️

2020-06-27 14:41 UTC, rezaerami approved these changes

2020-06-27 14:41 UTC, rezaerami commented on packages/ui/packages/IntegerInput/README.md
> +[![version](https://img.shields.io/npm/v/@snappmarket/ui-input.svg?style=flat-square)](https://www.npmjs.com/package/@snappmarket/ui-input)
fix the paths to the component on npm and github

2020-06-27 14:41 UTC, rezaerami commented on packages/ui/packages/IntegerInput/docz/demo.js
> +import IntegerInput from '..';
it's better to import the source of the input, cause when you import it this way, it will import the build version in docz

2020-06-27 14:41 UTC, rezaerami commented on packages/ui/packages/IntegerInput/docz/index.mdx
> +```jsx
it's recommended to have the raw version of the component in basic usage,, just like we did in many other components

2020-06-27 14:41 UTC, rezaerami commented on packages/ui/packages/IntegerInput/src/index.js
> +const isValid = (value, min, max) =>
since the validation is specific to this component, please move the validator inside, also it's recommended to use default props and shape prop type if you want to notify the developer to use it in the right way

2020-06-27 14:41 UTC, rezaerami commented on packages/ui/packages/IntegerInput/src/index.js
> +  pattern = `^-?[0-9]*$`,
since it's a numeric input, so it's better to put the pattern inside of the component instead of asking the developer to define it, besides, to set the default value, use defaultProps instead

2020-06-27 14:41 UTC, rezaerami commented on packages/ui/packages/IntegerInput/src/index.js
> +  const handleOnChange = event => {
when you enter a number, then you remove it, it sets zero as the value and you can't remove it

2020-06-27 14:41 UTC, rezaerami commented on packages/ui/packages/IntegerInput/src/index.js
> +  minMessage: PropTypes.string,
it's better to pass an object called messages or errors, with min, max and invalid properties that contain the user message, also define defaultProps for it, otherwise use isRequired flag to force the developer to pass the message

2020-06-27 14:41 UTC, rezaerami commented on packages/ui/packages/IntegerInput/src/index.js
> +      autoComplete="off"
instead, you can spread the rest props to input so developer will be free to add any other attribute to input

2020-06-27 14:41 UTC, rezaerami approved these changes

2020-06-27 15:18 UTC, sayjeyhi commented on packages/helpers/packages/NumberHelpers/index.js
> +      throw validationMessages.nanMessage;
فک کنم اینجا سه تا شرط ساده باید چک بشن، لازم نیست انقد try, catch اینا بزاری بعد throw کنی اونور بگیری و return کنی

2020-06-27 20:25 UTC, sayjeyhi approved these changes

2020-06-27 20:25 UTC, merged